import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
	id 'application'
	id 'maven-publish'
	id 'com.gradleup.shadow' version '8.3.11'
}

repositories {
	mavenCentral()
}

java {
	sourceCompatibility = targetCompatibility = JavaVersion.VERSION_1_8
}

application {
	mainClass = project.property('main_class')
}

dependencies {
	compileOnly 'org.ow2.asm:asm-debug-all:5.2'
	runtimeOnly 'org.ow2.asm:asm-all:5.2'
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = 'UTF-8'
}

tasks.withType(Javadoc).configureEach {
	options.encoding = 'UTF-8'
}

tasks.named('jar', Jar) {
	manifest {
		attributes 'Main-Class': project.property('main_class')
	}
}

tasks.named('shadowJar', ShadowJar) {
	relocate 'org.objectweb.asm', 'immibis.bon.org.objectweb.asm'
}

tasks.register('sourcesJar', Jar) {
	archiveClassifier.set('sources')
	from sourceSets.main.allSource
}

tasks.register('javadocJar', Jar) {
	archiveClassifier.set('javadoc')
	from javadoc
}

/* Task dependency */
tasks.named('assemble') {
	finalizedBy tasks.named('shadowJar')
}

publishing {
	publications {
		maven(MavenPublication) {
			from components.java
			artifact tasks.named('sourcesJar')
			artifact tasks.named('javadocJar')
		}
	}
}